apiVersion: v1
kind: Secret
metadata:
  name: gel-server-password
  namespace: gel
  labels:
    app: gel
    layer: infrastructure
    component: database
type: Opaque
stringData:
  password: "gel-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: gel-postgres-superuser
  namespace: gel
  labels:
    app: gel
    layer: infrastructure
    component: database
type: Opaque
stringData:
  username: postgres
  password: "supervisor-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: gel-postgres-user
  namespace: gel
  labels:
    app: gel
    layer: infrastructure
    component: database
type: Opaque
stringData:
  username: iforge
  password: "user-password"
  dsn: "postgres://iforge:user-password@gel-postgres-rw:5432/gel?sslmode=disable"
